# Generated by Django 5.0.6 on 2024-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_articles_articles_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_articles',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
