# Generated by Django 5.0.6 on 2024-05-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_articles_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_page',
            name='published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
