# Generated by Django 5.0.6 on 2024-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_page_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_page',
            name='published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='p', max_length=100),
        ),
    ]
