# Generated by Django 5.0.6 on 2024-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articles_page_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_page',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articles_page',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
