# Generated by Django 5.0.6 on 2024-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_page_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
