# Generated by Django 5.0.6 on 2024-06-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_page_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_page',
            name='is_active',
        ),
    ]
