# Generated by Django 5.0.6 on 2024-06-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_articles_page_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_page',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
