# Generated by Django 5.0.6 on 2024-06-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_page_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_page',
            name='short_description',
            field=models.TextField(),
        ),
    ]
