# Generated by Django 5.0.6 on 2024-06-30 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articles_page_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_page',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
