# Generated by Django 5.0.6 on 2024-07-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articlescomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescomment',
            options={'verbose_name': 'کامنت مقاله', 'verbose_name_plural': 'کامنت مقالات'},
        ),
    ]
