# Generated by Django 5.0.6 on 2024-07-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_articlescomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlescomment', verbose_name='والد'),
        ),
    ]
