# Generated by Django 5.0.6 on 2024-07-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articlescomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescomment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.articles_page', verbose_name='مقاله'),
            preserve_default=False,
        ),
    ]
