# Generated by Django 5.0.6 on 2024-07-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_articlescomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_page',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='articles.category_articles'),
        ),
    ]
