# Generated by Django 5.0.6 on 2024-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0003_english_vocabs_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english_vocabs',
            name='cat',
            field=models.ManyToManyField(blank=True, null=True, to='vocabs.category_languages'),
        ),
    ]
