# Generated by Django 5.0.6 on 2024-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litnerapp',
            name='dl',
            field=models.DateField(),
        ),
    ]
