# Generated by Django 5.0.6 on 2024-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0002_alter_litnerapp_dl'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnerapp',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
