# Generated by Django 5.0.6 on 2024-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0003_litnerapp_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnerapp',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='litnerapp',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
