# Generated by Django 5.0.6 on 2024-07-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0005_premiumaccount_alter_litnerapp_options_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='منقضی شده'),
        ),
    ]
