# Generated by Django 5.0.6 on 2024-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
