# Generated by Django 5.0.6 on 2024-05-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_image',
        ),
    ]
