# Generated by Django 5.0.6 on 2024-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_moreinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinformation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
