# Generated by Django 5.0.6 on 2024-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_moreinformation_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinformation',
            name='address',
        ),
        migrations.AlterField(
            model_name='moreinformation',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
