# Generated by Django 5.0.6 on 2024-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_moreinformation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinformation',
            name='changepass',
            field=models.BooleanField(default=False),
        ),
    ]
