# Generated by Django 5.0.6 on 2024-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('url_title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='poster/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پوستر',
                'verbose_name_plural': 'پوستر ها',
            },
        ),
    ]
