# Generated by Django 5.0.6 on 2024-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='توضیحات کوتاه'),
        ),
    ]
